export const fallbackWords = {
  5: ["CHIEN", "TABLE", "POMME"],
  6: ["MAISON", "FLEURS", "JARDIN"],
  7: ["ANIMAUX", "BATEAUX", "VOITURE"],
    8: ["ACCABLEE", "VENITIEN", "ELEPHANT"],
    9: ["PARAPLUIE", "TELEPHONE", "CHOCOLATS"],
    10: ["ORDINATEUR", "SOUSCRITES", "RECOMMENCE"], 
    11: ["CHOCOLATIER", "DEVELOPPEUR", "INTERACTION"],
    12: ["BIBLIOTHEQUE", "INFORMATIQUE", "CONSTRUCTION"]
};